/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodoRouteImport } from './routes/_authenticated/todo'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedRevenusRouteImport } from './routes/_authenticated/revenus'
import { Route as AuthenticatedMessengerRouteImport } from './routes/_authenticated/messenger'
import { Route as AuthenticatedLivraisonRouteImport } from './routes/_authenticated/livraison'
import { Route as AuthenticatedFacturesRouteImport } from './routes/_authenticated/factures'
import { Route as AuthenticatedDevisRouteImport } from './routes/_authenticated/devis'
import { Route as AuthenticatedCreationDevisRouteImport } from './routes/_authenticated/creation-devis'
import { Route as AuthenticatedCommandesRouteImport } from './routes/_authenticated/commandes'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBonsLivraisonRouteImport } from './routes/_authenticated/bons-livraison'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedCommandesIndexRouteImport } from './routes/_authenticated/commandes.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedAdministrationIndexRouteImport } from './routes/_authenticated/administration.index'
import { Route as AuthenticatedCommandesNouvelleRouteImport } from './routes/_authenticated/commandes.nouvelle'
import { Route as AuthenticatedCommandesDuJourRouteImport } from './routes/_authenticated/commandes.du-jour'
import { Route as AuthenticatedCommandesIdRouteImport } from './routes/_authenticated/commandes.$id'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedAdministrationUtilisateursRouteImport } from './routes/_authenticated/administration/utilisateurs'
import { Route as AuthenticatedAdministrationSecuriteRouteImport } from './routes/_authenticated/administration/securite'
import { Route as AuthenticatedAdministrationDisponibiliteRouteImport } from './routes/_authenticated/administration/disponibilite'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodoRoute = AuthenticatedTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevenusRoute = AuthenticatedRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessengerRoute = AuthenticatedMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLivraisonRoute = AuthenticatedLivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacturesRoute = AuthenticatedFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevisRoute = AuthenticatedDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreationDevisRoute =
  AuthenticatedCreationDevisRouteImport.update({
    id: '/creation-devis',
    path: '/creation-devis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandesRoute = AuthenticatedCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBonsLivraisonRoute =
  AuthenticatedBonsLivraisonRouteImport.update({
    id: '/bons-livraison',
    path: '/bons-livraison',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandesIndexRoute =
  AuthenticatedCommandesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommandesRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedAdministrationIndexRoute =
  AuthenticatedAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedCommandesNouvelleRoute =
  AuthenticatedCommandesNouvelleRouteImport.update({
    id: '/nouvelle',
    path: '/nouvelle',
    getParentRoute: () => AuthenticatedCommandesRoute,
  } as any)
const AuthenticatedCommandesDuJourRoute =
  AuthenticatedCommandesDuJourRouteImport.update({
    id: '/du-jour',
    path: '/du-jour',
    getParentRoute: () => AuthenticatedCommandesRoute,
  } as any)
const AuthenticatedCommandesIdRoute =
  AuthenticatedCommandesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCommandesRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedAdministrationUtilisateursRoute =
  AuthenticatedAdministrationUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationSecuriteRoute =
  AuthenticatedAdministrationSecuriteRouteImport.update({
    id: '/securite',
    path: '/securite',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationDisponibiliteRoute =
  AuthenticatedAdministrationDisponibiliteRouteImport.update({
    id: '/disponibilite',
    path: '/disponibilite',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bons-livraison': typeof AuthenticatedBonsLivraisonRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/commandes': typeof AuthenticatedCommandesRouteWithChildren
  '/creation-devis': typeof AuthenticatedCreationDevisRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/livraison': typeof AuthenticatedLivraisonRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/revenus': typeof AuthenticatedRevenusRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/todo': typeof AuthenticatedTodoRoute
  '/administration/disponibilite': typeof AuthenticatedAdministrationDisponibiliteRoute
  '/administration/securite': typeof AuthenticatedAdministrationSecuriteRoute
  '/administration/utilisateurs': typeof AuthenticatedAdministrationUtilisateursRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/commandes/du-jour': typeof AuthenticatedCommandesDuJourRoute
  '/commandes/nouvelle': typeof AuthenticatedCommandesNouvelleRoute
  '/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bons-livraison': typeof AuthenticatedBonsLivraisonRoute
  '/creation-devis': typeof AuthenticatedCreationDevisRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/livraison': typeof AuthenticatedLivraisonRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/revenus': typeof AuthenticatedRevenusRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/todo': typeof AuthenticatedTodoRoute
  '/administration/disponibilite': typeof AuthenticatedAdministrationDisponibiliteRoute
  '/administration/securite': typeof AuthenticatedAdministrationSecuriteRoute
  '/administration/utilisateurs': typeof AuthenticatedAdministrationUtilisateursRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/commandes/du-jour': typeof AuthenticatedCommandesDuJourRoute
  '/commandes/nouvelle': typeof AuthenticatedCommandesNouvelleRoute
  '/administration': typeof AuthenticatedAdministrationIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/commandes': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bons-livraison': typeof AuthenticatedBonsLivraisonRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/commandes': typeof AuthenticatedCommandesRouteWithChildren
  '/_authenticated/creation-devis': typeof AuthenticatedCreationDevisRoute
  '/_authenticated/devis': typeof AuthenticatedDevisRoute
  '/_authenticated/factures': typeof AuthenticatedFacturesRoute
  '/_authenticated/livraison': typeof AuthenticatedLivraisonRoute
  '/_authenticated/messenger': typeof AuthenticatedMessengerRoute
  '/_authenticated/revenus': typeof AuthenticatedRevenusRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/todo': typeof AuthenticatedTodoRoute
  '/_authenticated/administration/disponibilite': typeof AuthenticatedAdministrationDisponibiliteRoute
  '/_authenticated/administration/securite': typeof AuthenticatedAdministrationSecuriteRoute
  '/_authenticated/administration/utilisateurs': typeof AuthenticatedAdministrationUtilisateursRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/_authenticated/commandes/du-jour': typeof AuthenticatedCommandesDuJourRoute
  '/_authenticated/commandes/nouvelle': typeof AuthenticatedCommandesNouvelleRoute
  '/_authenticated/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administration'
    | '/analytics'
    | '/bons-livraison'
    | '/clients'
    | '/commandes'
    | '/creation-devis'
    | '/devis'
    | '/factures'
    | '/livraison'
    | '/messenger'
    | '/revenus'
    | '/tableau-de-bord'
    | '/todo'
    | '/administration/disponibilite'
    | '/administration/securite'
    | '/administration/utilisateurs'
    | '/clients/$clientId'
    | '/commandes/$id'
    | '/commandes/du-jour'
    | '/commandes/nouvelle'
    | '/administration/'
    | '/clients/'
    | '/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/bons-livraison'
    | '/creation-devis'
    | '/devis'
    | '/factures'
    | '/livraison'
    | '/messenger'
    | '/revenus'
    | '/tableau-de-bord'
    | '/todo'
    | '/administration/disponibilite'
    | '/administration/securite'
    | '/administration/utilisateurs'
    | '/clients/$clientId'
    | '/commandes/$id'
    | '/commandes/du-jour'
    | '/commandes/nouvelle'
    | '/administration'
    | '/clients'
    | '/commandes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/administration'
    | '/_authenticated/analytics'
    | '/_authenticated/bons-livraison'
    | '/_authenticated/clients'
    | '/_authenticated/commandes'
    | '/_authenticated/creation-devis'
    | '/_authenticated/devis'
    | '/_authenticated/factures'
    | '/_authenticated/livraison'
    | '/_authenticated/messenger'
    | '/_authenticated/revenus'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/todo'
    | '/_authenticated/administration/disponibilite'
    | '/_authenticated/administration/securite'
    | '/_authenticated/administration/utilisateurs'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/commandes/$id'
    | '/_authenticated/commandes/du-jour'
    | '/_authenticated/commandes/nouvelle'
    | '/_authenticated/administration/'
    | '/_authenticated/clients/'
    | '/_authenticated/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/todo': {
      id: '/_authenticated/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AuthenticatedTodoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenus': {
      id: '/_authenticated/revenus'
      path: '/revenus'
      fullPath: '/revenus'
      preLoaderRoute: typeof AuthenticatedRevenusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messenger': {
      id: '/_authenticated/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof AuthenticatedMessengerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/livraison': {
      id: '/_authenticated/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof AuthenticatedLivraisonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/factures': {
      id: '/_authenticated/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AuthenticatedFacturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis': {
      id: '/_authenticated/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof AuthenticatedDevisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creation-devis': {
      id: '/_authenticated/creation-devis'
      path: '/creation-devis'
      fullPath: '/creation-devis'
      preLoaderRoute: typeof AuthenticatedCreationDevisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commandes': {
      id: '/_authenticated/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof AuthenticatedCommandesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bons-livraison': {
      id: '/_authenticated/bons-livraison'
      path: '/bons-livraison'
      fullPath: '/bons-livraison'
      preLoaderRoute: typeof AuthenticatedBonsLivraisonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commandes/': {
      id: '/_authenticated/commandes/'
      path: '/'
      fullPath: '/commandes/'
      preLoaderRoute: typeof AuthenticatedCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedCommandesRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/administration/': {
      id: '/_authenticated/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof AuthenticatedAdministrationIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/commandes/nouvelle': {
      id: '/_authenticated/commandes/nouvelle'
      path: '/nouvelle'
      fullPath: '/commandes/nouvelle'
      preLoaderRoute: typeof AuthenticatedCommandesNouvelleRouteImport
      parentRoute: typeof AuthenticatedCommandesRoute
    }
    '/_authenticated/commandes/du-jour': {
      id: '/_authenticated/commandes/du-jour'
      path: '/du-jour'
      fullPath: '/commandes/du-jour'
      preLoaderRoute: typeof AuthenticatedCommandesDuJourRouteImport
      parentRoute: typeof AuthenticatedCommandesRoute
    }
    '/_authenticated/commandes/$id': {
      id: '/_authenticated/commandes/$id'
      path: '/$id'
      fullPath: '/commandes/$id'
      preLoaderRoute: typeof AuthenticatedCommandesIdRouteImport
      parentRoute: typeof AuthenticatedCommandesRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/administration/utilisateurs': {
      id: '/_authenticated/administration/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/administration/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdministrationUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/securite': {
      id: '/_authenticated/administration/securite'
      path: '/securite'
      fullPath: '/administration/securite'
      preLoaderRoute: typeof AuthenticatedAdministrationSecuriteRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/disponibilite': {
      id: '/_authenticated/administration/disponibilite'
      path: '/disponibilite'
      fullPath: '/administration/disponibilite'
      preLoaderRoute: typeof AuthenticatedAdministrationDisponibiliteRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
  }
}

interface AuthenticatedAdministrationRouteChildren {
  AuthenticatedAdministrationDisponibiliteRoute: typeof AuthenticatedAdministrationDisponibiliteRoute
  AuthenticatedAdministrationSecuriteRoute: typeof AuthenticatedAdministrationSecuriteRoute
  AuthenticatedAdministrationUtilisateursRoute: typeof AuthenticatedAdministrationUtilisateursRoute
  AuthenticatedAdministrationIndexRoute: typeof AuthenticatedAdministrationIndexRoute
}

const AuthenticatedAdministrationRouteChildren: AuthenticatedAdministrationRouteChildren =
  {
    AuthenticatedAdministrationDisponibiliteRoute:
      AuthenticatedAdministrationDisponibiliteRoute,
    AuthenticatedAdministrationSecuriteRoute:
      AuthenticatedAdministrationSecuriteRoute,
    AuthenticatedAdministrationUtilisateursRoute:
      AuthenticatedAdministrationUtilisateursRoute,
    AuthenticatedAdministrationIndexRoute:
      AuthenticatedAdministrationIndexRoute,
  }

const AuthenticatedAdministrationRouteWithChildren =
  AuthenticatedAdministrationRoute._addFileChildren(
    AuthenticatedAdministrationRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedCommandesRouteChildren {
  AuthenticatedCommandesIdRoute: typeof AuthenticatedCommandesIdRoute
  AuthenticatedCommandesDuJourRoute: typeof AuthenticatedCommandesDuJourRoute
  AuthenticatedCommandesNouvelleRoute: typeof AuthenticatedCommandesNouvelleRoute
  AuthenticatedCommandesIndexRoute: typeof AuthenticatedCommandesIndexRoute
}

const AuthenticatedCommandesRouteChildren: AuthenticatedCommandesRouteChildren =
  {
    AuthenticatedCommandesIdRoute: AuthenticatedCommandesIdRoute,
    AuthenticatedCommandesDuJourRoute: AuthenticatedCommandesDuJourRoute,
    AuthenticatedCommandesNouvelleRoute: AuthenticatedCommandesNouvelleRoute,
    AuthenticatedCommandesIndexRoute: AuthenticatedCommandesIndexRoute,
  }

const AuthenticatedCommandesRouteWithChildren =
  AuthenticatedCommandesRoute._addFileChildren(
    AuthenticatedCommandesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBonsLivraisonRoute: typeof AuthenticatedBonsLivraisonRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedCommandesRoute: typeof AuthenticatedCommandesRouteWithChildren
  AuthenticatedCreationDevisRoute: typeof AuthenticatedCreationDevisRoute
  AuthenticatedDevisRoute: typeof AuthenticatedDevisRoute
  AuthenticatedFacturesRoute: typeof AuthenticatedFacturesRoute
  AuthenticatedLivraisonRoute: typeof AuthenticatedLivraisonRoute
  AuthenticatedMessengerRoute: typeof AuthenticatedMessengerRoute
  AuthenticatedRevenusRoute: typeof AuthenticatedRevenusRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedTodoRoute: typeof AuthenticatedTodoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministrationRoute:
    AuthenticatedAdministrationRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBonsLivraisonRoute: AuthenticatedBonsLivraisonRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedCommandesRoute: AuthenticatedCommandesRouteWithChildren,
  AuthenticatedCreationDevisRoute: AuthenticatedCreationDevisRoute,
  AuthenticatedDevisRoute: AuthenticatedDevisRoute,
  AuthenticatedFacturesRoute: AuthenticatedFacturesRoute,
  AuthenticatedLivraisonRoute: AuthenticatedLivraisonRoute,
  AuthenticatedMessengerRoute: AuthenticatedMessengerRoute,
  AuthenticatedRevenusRoute: AuthenticatedRevenusRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedTodoRoute: AuthenticatedTodoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
