ALTER TABLE public.commandes DISABLE TRIGGER USER;
ALTER TABLE public.reminders DISABLE TRIGGER USER;
ALTER TABLE public.commande_items DISABLE TRIGGER USER;
ALTER TABLE public.bons_livraison DISABLE TRIGGER USER;
ALTER TABLE public.factures DISABLE TRIGGER USER;
ALTER TABLE public.devis DISABLE TRIGGER USER;